from typing import List, Dict, Any

SEED_STATIONS: List[Dict[str, Any]] = [
    {
        "id": "IMD-RJ-04",
        "name": "Jaisalmer",
        "state": "Rajasthan",
        "lat": 26.9157,
        "lng": 70.9083,
        "zone": "Arid / Thar Desert",
        "elevation": 225.0,
        "base_temp": 38.5,
        "base_humidity": 24.0,
        "base_pressure": 1002.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-RJ-05",
        "name": "Bikaner",
        "state": "Rajasthan",
        "lat": 28.0229,
        "lng": 73.3119,
        "zone": "Arid / Thar Desert",
        "elevation": 242.0,
        "base_temp": 37.8,
        "base_humidity": 26.0,
        "base_pressure": 1003.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-RJ-06",
        "name": "Jodhpur",
        "state": "Rajasthan",
        "lat": 26.2389,
        "lng": 73.0243,
        "zone": "Arid / Thar Desert",
        "elevation": 231.0,
        "base_temp": 37.2,
        "base_humidity": 28.0,
        "base_pressure": 1004.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-DL-01",
        "name": "New Delhi (Safdarjung)",
        "state": "Delhi",
        "lat": 28.5840,
        "lng": 77.2065,
        "zone": "Composite / Urban",
        "elevation": 216.0,
        "base_temp": 33.0,
        "base_humidity": 55.0,
        "base_pressure": 1008.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-DL-02",
        "name": "Palam (IGI Airport)",
        "state": "Delhi",
        "lat": 28.5665,
        "lng": 77.1031,
        "zone": "Composite / Urban",
        "elevation": 237.0,
        "base_temp": 33.5,
        "base_humidity": 52.0,
        "base_pressure": 1007.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-MH-01",
        "name": "Mumbai (Colaba)",
        "state": "Maharashtra",
        "lat": 18.9067,
        "lng": 72.8147,
        "zone": "Coastal",
        "elevation": 11.0,
        "base_temp": 31.0,
        "base_humidity": 82.0,
        "base_pressure": 1012.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-MH-02",
        "name": "Mumbai (Santacruz)",
        "state": "Maharashtra",
        "lat": 19.0896,
        "lng": 72.8656,
        "zone": "Coastal",
        "elevation": 14.0,
        "base_temp": 31.5,
        "base_humidity": 80.0,
        "base_pressure": 1011.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-ML-01",
        "name": "Cherrapunji",
        "state": "Meghalaya",
        "lat": 25.2986,
        "lng": 91.5822,
        "zone": "High Rainfall",
        "elevation": 1313.0,
        "base_temp": 21.0,
        "base_humidity": 92.0,
        "base_pressure": 870.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-ML-02",
        "name": "Mawsynram",
        "state": "Meghalaya",
        "lat": 25.2974,
        "lng": 91.5828,
        "zone": "High Rainfall",
        "elevation": 1400.0,
        "base_temp": 20.8,
        "base_humidity": 94.0,
        "base_pressure": 868.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-HP-01",
        "name": "Shimla",
        "state": "Himachal Pradesh",
        "lat": 31.1048,
        "lng": 77.1734,
        "zone": "Montane / Himalayan",
        "elevation": 2205.0,
        "base_temp": 17.5,
        "base_humidity": 60.0,
        "base_pressure": 780.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-UT-01",
        "name": "Leh",
        "state": "Ladakh",
        "lat": 34.1526,
        "lng": 77.5771,
        "zone": "Cold Desert",
        "elevation": 3500.0,
        "base_temp": 12.0,
        "base_humidity": 30.0,
        "base_pressure": 670.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-TN-01",
        "name": "Chennai (Meenambakkam)",
        "state": "Tamil Nadu",
        "lat": 12.9941,
        "lng": 80.1709,
        "zone": "Coastal",
        "elevation": 16.0,
        "base_temp": 34.0,
        "base_humidity": 78.0,
        "base_pressure": 1010.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-MH-03",
        "name": "Nagpur",
        "state": "Maharashtra",
        "lat": 21.1458,
        "lng": 79.0882,
        "zone": "Central Semi-Arid",
        "elevation": 310.0,
        "base_temp": 36.5,
        "base_humidity": 45.0,
        "base_pressure": 980.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-WB-01",
        "name": "Kolkata (Alipore)",
        "state": "West Bengal",
        "lat": 22.5334,
        "lng": 88.3243,
        "zone": "Gangetic Delta",
        "elevation": 9.0,
        "base_temp": 32.5,
        "base_humidity": 85.0,
        "base_pressure": 1011.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    },
    {
        "id": "IMD-KA-01",
        "name": "Bengaluru",
        "state": "Karnataka",
        "lat": 12.9716,
        "lng": 77.5946,
        "zone": "Deccan Plateau",
        "elevation": 920.0,
        "base_temp": 27.0,
        "base_humidity": 65.0,
        "base_pressure": 920.0,
        "sensor_types": ["temperature", "humidity", "pressure", "wind_speed", "wind_direction", "rainfall"]
    }
]
